apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'com.folio.poc'
version = '0.1.0'

android {
  namespace 'com.folio.poc'
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
    minSdkVersion 28
    consumerProguardFiles 'consumer-rules.pro'
  }
  sourceSets.main.java.srcDirs += 'generated'
}

dependencies {
  implementation 'net.java.dev.jna:jna:5.19.1@aar'
}
